sudo: required
services:
  - docker
before_install:
  - docker build -t kkaneki/dev-client -f ./client/Dockerfile.dev ./client
scripts:
  - docker run -e CI=true kkaneki/dev-client npm run test -- --coverage

after_success:
  - docker build -t kkaneki/client ./client
  - docker build -t kkaneki/nginx ./nginx
  - docker build -t kkaneki/server ./server
  - docker build -t kkaneki/worker ./worker
  # LOGIN TO docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kkaneki/client
  - docker push kkaneki/nginx
  - docker push kkaneki/server
  - docker push kkaneki/worker