version: "3.3"
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: redis
    api:
        build:
            context: server
            dockerfile: Dockerfile.dev
        volumes:
            - ./server:/usr/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - ./client:/usr/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - ./worker:/usr/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports: 
            - 80:80
        depends_on: 
            - api
            - client